import { useState, useMemo } from 'react';
import { Copy, Download, FileText, FileDown, Save, Check, Sparkles, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';
import { generatePrompt, calculateQualityScore, getTextStats } from '../utils/promptGenerator';
import { generateProfessionalPrompt } from '../utils/geminiService';
import './PreviewPanel.css';

export default function PreviewPanel({ fields, category, onSave, isEditing }) {
  const [copied, setCopied] = useState(false);
  const [title, setTitle] = useState('');
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const rawPrompt = useMemo(() => generatePrompt(fields), [fields]);
  const displayPrompt = aiPrompt || rawPrompt;

  const quality = useMemo(() => calculateQualityScore(fields), [fields]);
  const stats = useMemo(() => getTextStats(displayPrompt), [displayPrompt]);

  const qualityLabel = quality >= 80 ? 'Excellent' : quality >= 50 ? 'Good' : quality >= 20 ? 'Needs work' : 'Just started';
  const qualityColor = quality >= 80 ? 'var(--success)' : quality >= 50 ? 'var(--accent)' : quality >= 20 ? 'var(--warning)' : 'var(--text-muted)';

  const handleGenerateAI = async () => {
    if (!fields.role?.trim() || !fields.task?.trim()) {
      toast.error('⚠️ Please fill at least Role and Task before generating a prompt.');
      return;
    }
    setIsGenerating(true);
    try {
      const result = await generateProfessionalPrompt(fields);
      setAiPrompt(result);
      toast.success('✅ Prompt generated successfully!');
    } catch (err) {
      toast.error(err.message || 'Generate karne mein masla aaya');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = async () => {
    if (!displayPrompt.trim()) {
      toast.error('Nothing to copy yet');
      return;
    }
    await navigator.clipboard.writeText(displayPrompt);
    setCopied(true);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopied(false), 1500);
  };

  const handleExportTXT = () => {
    if (!displayPrompt.trim()) return toast.error('Nothing to export yet');
    const blob = new Blob([displayPrompt], { type: 'text/plain' });
    downloadBlob(blob, `${title || 'prompt'}.txt`);
    toast.success('Downloaded as TXT');
  };

  const handleExportMarkdown = () => {
    if (!displayPrompt.trim()) return toast.error('Nothing to export yet');
    const blob = new Blob([displayPrompt], { type: 'text/markdown' });
    downloadBlob(blob, `${title || 'prompt'}.md`);
    toast.success('Downloaded as Markdown');
  };

  const handleExportPDF = () => {
    if (!displayPrompt.trim()) return toast.error('Nothing to export yet');
    const doc = new jsPDF();
    const lines = doc.splitTextToSize(displayPrompt, 180);
    doc.setFontSize(11);
    doc.text(lines, 15, 20);
    doc.save(`${title || 'prompt'}.pdf`);
    toast.success('Downloaded as PDF');
  };

  const handleSaveClick = () => {
    const finalTitle = title.trim() || `${category} prompt`;
    onSave(finalTitle, displayPrompt);
  };

  return (
    <div className="preview-card card">
      <div className="preview-header">
        <h2>Live Preview</h2>
        <span className="ai-badge-top">✨ Powered by Google Gemini AI</span>
        <div className="quality-gauge" style={{ '--gauge-color': qualityColor, '--gauge-percent': `${quality}%` }}>
          <svg viewBox="0 0 36 36" className="gauge-svg">
            <path className="gauge-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
            <path
              className="gauge-fill"
              strokeDasharray={`${quality}, 100`}
              d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
            />
          </svg>
          <div className="gauge-text">
            <span className="gauge-score">{quality}</span>
          </div>
        </div>
      </div>
      <div className="quality-label" style={{ color: qualityColor }}>{qualityLabel} quality</div>

      <input
        className="title-input"
        placeholder="Enter Prompt Title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />

      <button
        className="btn btn-primary generate-ai-btn"
        onClick={handleGenerateAI}
        disabled={isGenerating}
      >
        {isGenerating ? <Loader2 size={16} className="spin" /> : <Sparkles size={16} />}
        {isGenerating ? '🤖 Gemini AI is generating your professional prompt...' : aiPrompt ? 'Regenerate' : 'Generate AI Prompt'}
      </button>

      {aiPrompt && (
        <div className="ai-badge">✨ AI-generated by Gemini</div>
      )}
      {displayPrompt.trim() && (
      <div className="ai-power-badge">✨ Powered by Google Gemini AI</div>
      )}
      <div className="preview-box">
        {displayPrompt.trim() ? (
          <pre className="preview-text mono">{displayPrompt}</pre>
        ) : (
          <div className="preview-empty">
           Fill the form and click "Generate AI Prompt" — your AI-crafted prompt will appear here.
          </div>
        )}
      </div>

      <div className="preview-stats">
        {stats.words} words · {stats.characters} characters
      </div>

      <div className="preview-actions">
        <button className="btn btn-primary" onClick={handleSaveClick} disabled={!displayPrompt.trim()}>
          <Save size={16} />
          {isEditing ? 'Update Prompt' : 'Save Prompt'}
        </button>
        <button className="btn btn-secondary" onClick={handleCopy} disabled={!displayPrompt.trim()}>
          {copied ? <Check size={16} /> : <Copy size={16} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
        <button className="btn btn-secondary" onClick={handleExportTXT} disabled={!displayPrompt.trim()}>
          <FileText size={16} />
          TXT
        </button>
        <button className="btn btn-secondary" onClick={handleExportMarkdown} disabled={!displayPrompt.trim()}>
          <FileDown size={16} />
          MD
        </button>
        <button className="btn btn-secondary" onClick={handleExportPDF} disabled={!displayPrompt.trim()}>
          <Download size={16} />
          PDF
        </button>
      </div>
    </div>
  );
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}